name: Test PR Changes that is without hardcoded AGENT_TOOLSDIRECTORY on macOS

on: 
  push:
    branches:
      - test-708
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, self-hosted]
        python-version: ['3.8.17', '3.9.18', '3.10.9', '3.11.1', '3.12.1']
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        # uses: actions/setup-python@v5
        uses: priya-kinthali/setup-python@test-708-new
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Check Python version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      
